# Generated by Django 5.2.8 on 2025-12-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('general_physician', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('orthopedic', 'Orthopedic Surgeon'), ('gynecologist', 'Gynecologist'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('ent', 'ENT Specialist'), ('ophthalmologist', 'Ophthalmologist'), ('dentist', 'Dentist'), ('urologist', 'Urologist'), ('nephrologist', 'Nephrologist'), ('gastroenterologist', 'Gastroenterologist'), ('endocrinologist', 'Endocrinologist')], max_length=50)),
                ('license_number', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
