# Generated by Django 5.2.8 on 2025-12-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('experience', models.CharField()),
                ('education', models.TextField()),
                ('fees', models.IntegerField()),
                ('DoctorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser')),
            ],
        ),
    ]
